### PR TITLE
634: Fix service list sorting

### LINKED ISSUE #634: [BUG] Service is moved to the end of the list after marking it active.
**Bug description:**

1. Create a service.
2. Mark the service Active in service list view.

The service is moved to the end of the list in service list view.

**Expected behavior:**

The service is **not** moved to the end of the list in service list view.

### PR DESCRIPTION
**Pull request by IgorKrupenja**
#634

### CODE REVIEW

File: GUI/src/components/ServicesTable/index.tsx [hunk 1]
```diff
@@ -231,6 +232,7 @@ const ServicesTable: FC<ServicesTableProps> = ({ isCommon = false }) => {
           }
         }}
         setSorting={(state: SortingState) => {
+          console.log("igor state", state);
```
Comment (1AhmedYasser) [inline GUI/src/components/ServicesTable/index.tsx]: Please remove this console.log

**Review by 1AhmedYasser — CHANGES_REQUESTED** [review]

**Comment by 1AhmedYasser** [comment]
Please fix sonar issues

**Comment by IgorKrupenja** [comment]
> Please fix sonar issues

The issue is from **old** code not written by me. I tried a few things but I am still getting a similar issue reported by Sonar Cloud. Do you have any ideas how to fix this?

If not, I suggest we create a separate issue to track this problem.

**Review by 1AhmedYasser — APPROVED** [review]
LGTM
